name: build and deploy the application
on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling repo
        uses: actions/checkout@v2
      - name: saying Hii
        run: echo "saying Hii"