name: build and deploy app
on: [push,pull_request]

jobs:
    job1:
      runs-on: ubuntu-latest
      env:
        DATABASE_HOSTNAME: "localhost"
        DATABASE_PORT: 5432
        DATABASE_PASSWORD: "Makrod"
        DATABASE_NAME: "fastapi"
        DATABASE_USERNAME: "postgres"
        SECRET_KEY: "jdshavkhksvjhdalsd61145546dsav514v6as4Fv5s6d5FGV"
        ALGORITHM: "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      steps:
        - name: pulling github repo
          uses: actions/checkout@v2
        - name: installing python
          uses: actions/setup-python@v2
          with:
            python-version: "3.9"
        - name: update pip
          run: python -m pip install --upgrade pip
        - name: Installing all our dependencies
          run: pip install -r requirements.txt
        - name: running the uvicorn
          run: uvicorn app.main:app 